export const product = [
  {
    id: 1,
    productname: "Panda printed Hoodies",
    description: "relaxed and stylish hoodie with firm stiching | Orange",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual1.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
    gender: "Men",
  },
  {
    id: 2,
    productname: "Anywhere Hood",
    description: "Super Comfortable Hoodie | 100% cotton | yellow ",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual2.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
    gender: "Men",
  },
  {
    id: 3,
    productname: "Rebell Womens Cotton High Waisted Skinny Jeans",
    description: "Pure Cotton | Women Skinny Jeans | White",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual3.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
    gender: "Women",
  },
  {
    id: 4,
    productname: "Yardsale Sweatshirt",
    description:
      "Meridian Knitted Quarter zip | Winter Delux release | ash grey",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual4.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 5,
    productname: "Monbebe Corduroy Biege Cardigan",
    description:
      "Beautiful and cozy | Made with a stretchy cotton fabric with fleeced inside | comfy and warm ",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual8.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 6,
    productname: "Levis Light Blue Wash Denim Jacket",
    description:
      "perfect for men or women, for an oversized or fitted style | Light Blue Wash",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual5.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 7,
    productname: "Majestic Athletic Joggers",
    description: "Bottoms Pants Jog Bottoms | black",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual11.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 8,
    productname: "Large size looze Straight Jeans",
    description: "Fashionable Large Size Loose Cargo Casual Pants",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual7.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 9,
    productname: "ASOS design gingham skinny trouser",
    description:
      "Stretch waist gingham design skinny fit | cut very closely from hips to hem",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual9.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 10,
    productname: "Men's Jacket with Collar",
    description:
      "Masculine Style | Light lining and in a straight and spacious model | Black",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual6.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 11,
    productname: "Arden Pants Sweatpant",
    description: "Elastic Cotton fiber | grey",
    price: 3900,
    category: "Casuals",
    quantity: 1,
    photo: "./image/Casual10.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 12,
    productname: "Apple iPhone 13",
    description: "(128GB) - Midnight",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/iphone13.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },
  {
    id: 13,
    productname: "OnePlus Nord Buds",
    description:
      "True Wireless Earbuds| 12.4mm Titanium Drivers | Playback:Up to 30hr case | 4-Mic Design",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/earbuds.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },
  {
    id: 14,
    productname: "Panasonic Econavi Washing Machine",
    description:
      "8 Kg | Fully-Automatic Top Loading Washing Machine (NA-F80V9LRB, Silver, Stain Master+)",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/washing_machine.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },
  {
    id: 15,
    productname: "JBL Tune 760NC",
    description:
      " Over Ear Active Noise Cancellation Headphones with Mic, up to 50 Hours Playtime, JBL Pure Bass, Google Fast Pair",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/headphone1.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },
  {
    id: 16,
    productname: "Sony WH-CH710N",
    description:
      "  Active Noise Cancelling Wireless Headphones Bluetooth Over The Ear Headset with Mic for Phone-Call, 35Hrs",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/headphone2.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },
  {
    id: 17,
    productname: "Echo Dot (4th Gen, 2020",
    description: "   New and improved smart speaker with Alexa (Black)",
    price: 8900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/alexa.jpg",
    stock: "In Stock",
    delivery: "Tommorow",
    subtotal: 0,
  },

  {
    id: 18,
    productname: "Sony Bravia",
    description:
      "164 cm (65 inches) XR series 4K Ultra HD Smart OLED Google TV XR-65A80J (Black) (2021 Model) | with Alexa Compatibility",
    price: 10500,
    category: "Electronics",
    quantity: 1,
    photo: "./image/sony QLED.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },
  {
    id: 19,
    productname: "Samsung Galaxy M53 5G ",
    description:
      "(Mystique Green, 6GB, 128GB Storage) | Travel Adapter to be Purchased Separately",
    price: 2900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/samsungm53.jpg",
    stock: "Out of stock",
    delivery: "Wednesday",
    subtotal: 0,
  },
  {
    id: 20,
    productname: "2021 Apple iPad Pro",
    description:
      "With Apple M1 chip (12.9-inch/32.77 cm, Wi-Fi, 128GB) - Silver (5th Generation)",
    price: 9900,
    category: "Electronics",
    quantity: 1,
    photo: "./image/ipad_pro.jpg",
    stock: "In Stock",
    delivery: "Today",
    subtotal: 0,
  },

  {
    id: 21,
    productname: "Apple Watch Series 7 ",
    description:
      "(GPS + Cellular, 41mm) - Gold Stainless Steel Case with Gold Milanese Loop",
    price: 5000,
    category: "Electronics",
    quantity: 1,
    photo: "./image/iwatch.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },

  {
    id: 22,
    productname: "Attitue Leather Lofers",
    description: "Fine leather , with shine and best quality finish ",
    price: 1999,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe.webp",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 23,
    productname: "Nike Air Strike Lite",
    description: "Neon Yellow | HYPERBEAST ",
    price: 8779,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe1.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 24,
    productname: "Nike Air Force 1",
    description: "White | '07 LV8 Men's Shoes | HANON",
    price: 8455,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe2.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 25,
    productname: "Attitue Leather Boots",
    description: "Fashonable Walking Shoes , with waterproof technology ",
    price: 4499,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe3.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 26,
    productname: "Giaros Pencil Heels",
    description: "Floral and Fasionable Designs | Premium quality Shoes",
    price: 3599,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe4.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 27,
    productname: "MOOMMO Women Kitten Heels",
    description: "Court Shoes | Silver glittered | pointed closed toe Sandals",
    price: 4759,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe5.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 28,
    productname: "Puma In Spirit",
    description: "Sneakers | Sleek Designs | Unisex Product",
    price: 2199,
    category: "Shoes",
    quantity: 1,
    photo: "./image/shoe6.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Unisex",
    subtotal: 0,
  },
  {
    id: 29,
    productname: "Nikon D750",
    description:
      "Full-Frame Mirrorless Interchangeable-Lens Camera (with 28-70mm F3.5-5.6 OSS Lens)",
    price: 3900,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },
  {
    id: 30,
    productname: "Oliver Peoples Coleridge Sun",
    description:
      "OV1186s Silver / Grey | Rounded metal frame with premium lens",
    price: 2399,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc1.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },
  {
    id: 31,
    productname: "Holzkern sunglasses",
    description: "The Enchanting (Cinnamon Wood/Matte Gold)",
    price: 2899,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc2.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },
  {
    id: 32,
    productname: "Rayban Retro",
    description: "Vintage Retro Style French Tan Aviator Sunglasses | for Men",
    price: 3900,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc3.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },
  {
    id: 33,
    productname: "Ferragamo Lyst",
    description: "Leather Studio Floral Tote Bag in white",
    price: 5499,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc4.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 34,
    productname: "Formula Joven",
    description: "Womens Camel plaited crossbody bag with chain",
    price: 1445,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc6.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 35,
    productname: "PRADA Cashier Lizard",
    description: "LIMITED EDITION | The Cashier style bags by PRADA",
    price: 3900,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc7.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 36,
    productname: "Sony Canon II",
    description:
      "Full-Frame Mirrorless Interchangeable-Lens Camera (with 28-70mm F3.5-5.6 OSS Lens)",
    price: 3900,
    category: "Other Accesories",
    quantity: 1,
    photo: "./image/Acc8.jpg",
    stock: "In Stock",
    delivery: "Tuesday",
    subtotal: 0,
  },

  {
    id: 37,
    productname: "Analog Black Dial Men's Watch-TW000R438 ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches1.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 38,
    productname: "Casual Analog Black Dial Men's Watch-3255NM01 ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches2.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 39,
    productname: "Analog Black Dial Men's Watch-3245NM02 ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches3.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 40,
    productname: "Analog Unisex Adult Wrist Watch (Black Dial, Black Band) ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches4.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Unisex",
    subtotal: 0,
  },
  {
    id: 41,
    productname: "CASIO Flash Edition Smart Watch with Activity Tracker ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches5.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 42,
    productname: "Fire-Boltt Ninja 3 Full Touch ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches6.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Women",
    subtotal: 0,
  },
  {
    id: 43,
    productname: "Noise ColorFit Pulse Grand Smart Watch ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches7.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 44,
    productname: "Athleisure Analog Black Dial Men's Watch ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches8.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 45,
    productname: "Neo Analog Men's Watch ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches9.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Men",
    subtotal: 0,
  },
  {
    id: 46,
    productname: "Analog Unisex Adult Wrist Watch ",
    description: "",
    price: 5000,
    category: "Watches",
    quantity: 1,
    photo: "./image/watches10.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    gender: "Unisex",
    subtotal: 0,
  },
  {
    id: 47,
    productname: "Tempur-Pedic TEMPUR-Cloudz",
    description: "Pillow for Sleeping, Standard, White",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor1.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 48,
    productname: "Vintage Ceramic Pitcher Ceramic Jug",
    description: "Flower pot, vase with handle, collection, kitchen, retro decoration",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor2.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 49,
    productname: "Ravenna Home Classic 3",
    description: " Light Semi-flush Mount Chandelier, Bulbs Included, 14.5 cms H, Dark Bronze",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor3.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 50,
    productname: "Hjn Ceramic Vase- Teal Vase for Home Decor",
    description: "Flower Vase for Centerpieces, Modern Decor Vases for Living Room/ Bookshelf/Mantel/ Home Decor Accents - Teal texture-Large-10.6",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor4.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 51,
    productname: "F8T5 Flourescent Light Bulbs - 12 cms",
    description: " Under Cabinet Bulb - Cool White 4100k 8 Watt Tube Bulb - Pack of 6",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor5.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 52,
    productname: "Artistic Weavers Chester",
    description: "Boho Moroccan Area Rug, 7 inches 10 cms x 10 inches 3 cms,Grey",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor6.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 53,
    productname: "[6 Pack] Vintage Edison Bulbs with Spiral Filament",
    description: "60W Dimmable E26/E27 G95 Round Globe Large Antique Light, Golden Finish Industrial Design Amber Warm 120V",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor7.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 54,
    productname: "ANswet Area Rug",
    description: "Modern Flannel Non-Slip Floor Mat Living Room Bedroom Tassels Carpet Home Decor Rectangle 4*6",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor8.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 55,
    productname: "Falmn Bed Pillows",
    description: "Hotel Quality Down Alternative Back Stomach and Side Sleeper Pillows Gusseted and Supportive",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor9.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 56,
    productname: "One Oak Park Ceramic Vases",
    description: " Modern, Geometric, Minimalist, Natural, Nordic, Centerpiece (Height 6.75, Width 7.5, Depth 3.5, Circular with Bottleneck)",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor10.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 57,
    productname: "Monolia Area Rugs 3' X 5'",
    description: "Machine Washable Rugs for Living Room - Perfect Rugs for Bedroom and Kitchen Rugs - Persian Printed Area Rug for Home Décor, Apartment Decor and Dining Rooms",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor11.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 58,
    productname: "White Ceramic Vases",
    description: "Differing Unique bowl Design for Home Décor",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor12.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 59,
    productname: "Rivet Modern Geometric Pattern Decorative Stoneware Vase",
    description: "Large Centerpiece, 12.25 inches H, White",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor13.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
  {
    id: 60,
    productname: "AXILIXI Crystal Chandelier Contemporary, 24 cms",
    description: " Modern Living Room Chandelier, K9 Crystal Ceiling Lights Fixtures, Round 5 Tiers Pendant Lighting Chandelier Black for Entryway Dining Room Staircase",
    price: 5000,
    category: "Decorating Items",
    quantity: 1,
    photo: "./image/Decor14.jpg",
    stock: "Out of Stock",
    delivery: "Thursday",
    subtotal: 0,
  },
];
